apiVersion: v1
kind: Service
metadata:
    name: "samplecluster-5bb0"
    labels:
        app: "samplecluster-5bb0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "samplecluster-5bb0"