on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n mytcs2023 -g mytcs20239b59-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n mytcs2023 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n mytcs2023 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n mytcs2023 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mytcs2023.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "Reddammabusireddy/votingapp" -t mytcs2023.azurecr.io/samplecluster:${{ github.sha }} --label dockerfile-path=Reddammabusireddy/votingapp
        docker push mytcs2023.azurecr.io/samplecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_samplecluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep samplecluster9a22-votingapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace samplecluster9a22-votingapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: samplecluster9a22-votingapp
        container-registry-url: mytcs2023.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: sampleclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: samplecluster9a22-votingapp
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mytcs2023.azurecr.io/samplecluster:${{ github.sha }}
        imagepullsecrets: |
          sampleclustedockerauth   
